weights: yolor_p6.pt
cfg: cfg/yolor_p6.cfg
data: ./data/coco128.yaml
hyp: ./data/hyp.scratch.1280.yaml
epochs: 500
batch_size: 1
img_size:
- 1280
- 720
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 0
project: runs/train
name: yolor_p6
exist_ok: false
total_batch_size: 1
world_size: 1
global_rank: -1
save_dir: runs/train/yolor_p6
